name: "RWA- PR build"
on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

permissions:
  id-token: write
  contents: read
  pull-requests: read

env:
  AZURE_RESOURCE_GROUP: pr-${{github.event.pull_request.number}}-rg

jobs:
  clean-up-existing:
    uses: ./.github/workflows/tear-down.yml
    with:
      environment: pr

  build-and-deploy:
    uses: ./.github/workflows/tear-down.yml
    with:
      environment: pr

  clean-up:
    uses: ./.github/workflows/tear-down.yml
    with:
      environment: pr


