on:
  workflow_dispatch:
    inputs:
      github_environment:
        required: true
        type: string

  workflow_call:
    inputs:
      github_environment:
        required: true
        type: string
      resource_group:
        required: false
        type: string
        default: ''
      azure_environment_name:
        required: false
        type: string
        default: ''

permissions:
  id-token: write
  contents: read

jobs:
  tear_down:
    continue-on-error: true
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    env:
      AZURE_ENV_NAME: ${{ inputs.azure_environment_name == '' &&  inputs.environment || inputs.azure_environment_name }}
      AZURE_RESOURCE_GROUP: "${{ inputs.resource_group == '' && vars.AZURE_RESOURCE_GROUP || inputs.resource_group }}"
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Log in with Azure (Federated Credentials)
        run: |
          azd auth login `
            --client-id "$Env:AZURE_CLIENT_ID" `
            --federated-credential-provider "github" `
            --tenant-id "$Env:AZURE_TENANT_ID" `
            --debug
        shell: pwsh

      - name: Azure Dev Down
        run: azd down --force --purge --no-prompt
